<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RamosPartGenerator.Core\RamosPartGenerator.Core.csproj" />
    <ProjectReference Include="..\RamosPartGenerator.Excel\RamosPartGenerator.Excel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\specs\*.json" Link="specs\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
