<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\RamosPartGenerator.Core\RamosPartGenerator.Core.csproj" />
    <ProjectReference Include="..\..\src\RamosPartGenerator.Excel\RamosPartGenerator.Excel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\RamosPartGenerator.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
